FROM node:20-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends \
  mysql-client \
  postgresql-client \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

CMD ["node", "dist/server.js"]